import Foundation

struct SymptomToSpecialtyData {
    static let symptomToSpecialty: [String: [String]] = [
        "chest pain": ["Cardiology"],
        "shortness of breath": ["Cardiology", "Pulmonology"],
        "palpitations": ["Cardiology"],
        "high blood pressure": ["Cardiology"],
        "swelling in legs": ["Cardiology"],
        "joint pain": ["Orthopedics"],
        "back pain": ["Orthopedics", "Neurology"],
        "knee pain": ["Orthopedics"],
        "shoulder pain": ["Orthopedics"],
        "fracture": ["Orthopedics"],
        "arthritis": ["Orthopedics"],
        "headache": ["Neurology"],
        "dizziness": ["Neurology", "ENT"],
        "numbness": ["Neurology"],
        "seizures": ["Neurology"],
        "memory loss": ["Neurology", "Psychiatry"],
        "irregular periods": ["Gynecology"],
        "pelvic pain": ["Gynecology", "Urology"],
        "vaginal bleeding": ["Gynecology"],
        "infertility": ["Gynecology"],
        "menopause symptoms": ["Gynecology"],
        "abdominal pain": ["Surgery", "Gastroenterology"],
        "hernia": ["Surgery"],
        "appendicitis": ["Surgery"],
        "gallstones": ["Surgery"],
        "swelling or lump": ["Surgery", "Oncology"],
        "rash": ["Dermatology"],
        "itching": ["Dermatology"],
        "skin redness": ["Dermatology"],
        "acne": ["Dermatology"],
        "hair loss": ["Dermatology"],
        "weight gain": ["Endocrinology"],
        "weight loss": ["Endocrinology", "Oncology"],
        "fatigue": ["Endocrinology", "General Medicine"],
        "diabetes": ["Endocrinology"],
        "thyroid issues": ["Endocrinology"],
        "ear pain": ["ENT"],
        "hearing loss": ["ENT"],
        "sore throat": ["ENT"],
        "nasal congestion": ["ENT"],
        "sinus pain": ["ENT"],
        "unexplained weight loss": ["Oncology", "Endocrinology"],
        "lump in breast": ["Oncology", "Surgery"],
        "persistent cough": ["Oncology", "Pulmonology"],
        "blood in urine": ["Oncology", "Urology"],
        "chronic pain": ["Oncology"],
        "anxiety": ["Psychiatry"],
        "depression": ["Psychiatry"],
        "insomnia": ["Psychiatry", "Neurology"],
        "mood swings": ["Psychiatry"],
        "stress": ["Psychiatry"],
        "painful urination": ["Urology"],
        "frequent urination": ["Urology"],
        "kidney pain": ["Urology"],
        "erectile dysfunction": ["Urology"],
        "fever in child": ["Pediatrics"],
        "child growth issues": ["Pediatrics"],
        "child vomiting": ["Pediatrics"],
        "child rash": ["Pediatrics", "Dermatology"],
        "child cough": ["Pediatrics"],
        "fever": ["General Medicine", "Pediatrics"],
        "cough": ["Pulmonology", "General Medicine"],
        "vomiting": ["Gastroenterology", "General Medicine"],
        "diarrhea": ["Gastroenterology"],
        "constipation": ["Gastroenterology"],
        "blurred vision": ["Ophthalmology", "Neurology"],
        "eye redness": ["Ophthalmology"],
        "difficulty swallowing": ["ENT", "Gastroenterology"],
        "jaundice": ["Gastroenterology", "Hepatology"],
        "night sweats": ["Oncology", "Endocrinology"],
        "tremors": ["Neurology"],
        "allergic reaction": ["Allergy and Immunology"],
        "wheezing": ["Pulmonology", "Allergy and Immunology"],
        "blood in stool": ["Gastroenterology", "Oncology"],
        "chronic fatigue": ["Endocrinology", "Rheumatology"],
        "double vision": ["Ophthalmology", "Neurology"],
        "chest tightness": ["Cardiology", "Pulmonology"],
        "muscle weakness": ["Neurology", "Rheumatology"],
        "persistent fever": ["Infectious Disease", "General Medicine"],
        "swollen lymph nodes": ["Oncology", "Infectious Disease"],
        "dry mouth": ["Endocrinology", "General Medicine"],
        "heartburn": ["Gastroenterology"],
        "skin lesions": ["Dermatology", "Oncology"],
        "tinnitus": ["ENT"],
        "urinary incontinence": ["Urology", "Gynecology"],
        "bone pain": ["Orthopedics", "Oncology"],
        "recurrent infections": ["Infectious Disease", "Allergy and Immunology"],
        "confusion": ["Neurology", "Psychiatry"],
        "heavy menstrual bleeding": ["Gynecology"],
        "dark urine": ["Nephrology", "Hepatology"]
    ]
}

